environment:
  matrix:
    - nodejs_version: 0.10

# Get the latest stable version of Node 0.STABLE.latest
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off

before_test:
  - npm install grunt-cli -g

test_script:
  - node --version
  - npm --version
  - npm test
